export const rows = [
  {
    id: 1,
    RegisterId: 12345,
    Name: "John Doe",
    Age: 25,
    Phone: "+123456789",
    Email: "john.doe@example.com",
    Address: "123 Main St, Anytown USA",
    City: "Anytown",
    ZipCode: 12345,
  },
  {
    id: 2,
    RegisterId: 67890,
    Name: "Jane Smith",
    Age: 30,
    Phone: "+987654321",
    Email: "jane.smith@example.com",
    Address: "456 Elm St, Anytown USA",
    City: "Anytown",
    ZipCode: 67890,
  },
  {
    id: 3,
    RegisterId: 11111,
    Name: "Bob Johnson",
    Age: 35,
    Phone: "+555555555",
    Email: "bob.johnson@example.com",
    Address: "789 Oak St, Anytown USA",
    City: "Anytown",
    ZipCode: 11111,
  },
  {
    id: 4,
    RegisterId: 22222,
    Name: "Alice Brown",
    Age: 20,
    Phone: "+666666666",
    Email: "alice.brown@example.com",
    Address: "333 Pine St, Anytown USA",
    City: "Anytown",
    ZipCode: 22222,
  },
  {
    id: 5,
    RegisterId: 33333,
    Name: "Mike Davis",
    Age: 40,
    Phone: "+777777777",
    Email: "mike.davis@example.com",
    Address: "555 Maple St, Anytown USA",
    City: "Anytown",
    ZipCode: 33333,
  },
  {
    id: 6,
    RegisterId: 44444,
    Name: "Emily Wilson",
    Age: 28,
    Phone: "+888888888",
    Email: "emily.wilson@example.com",
    Address: "666 Spruce St, Anytown USA",
    City: "Anytown",
    ZipCode: 44444,
  },
];
export const columns = [
  {
    field: "id",
    headerName: "Id",
    align: "center",
    headerAlign: "center",
    width: 33,
  },
  {
    field: "Name",
    headerName: "Name",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "Email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  { field: "Age", headerName: "Age", align: "center", headerAlign: "center" },
  {
    field: "Phone",
    headerName: "Phone",
    width: 200,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "Address",
    headerName: "Address",
    width: 200,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "City",
    headerName: "City",
    width: 200,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "ZipCode",
    headerName: "ZipCode",
    width: 200,
    align: "center",
    headerAlign: "center",
  },
];
