export const rows = [
  {
    id: 1,
    Name: "John Doe",
    Email: "john.doe@example.com",
    Age: 25,
    Phone: "+123456789",
    Access: "admin",
  },
  {
    id: 2,
    Name: "Jane Smith",
    Email: "jane.smith@example.com",
    Age: 30,
    Phone: "+987654321",
    Access: "user",
  },
  {
    id: 3,
    Name: "Bob Johnson",
    Email: "bob.johnson@example.com",
    Age: 35,
    Phone: "+555555555",
    Access: "manager",
  },
  {
    id: 4,
    Name: "Alice Brown",
    Email: "alice.brown@example.com",
    Age: 20,
    Phone: "+666666666",
    Access: "admin",
  },
  {
    id: 5,
    Name: "Mike Davis",
    Email: "mike.davis@example.com",
    Age: 40,
    Phone: "+777777777",
    Access: "user",
  },
  {
    id: 6,
    Name: "Emily Wilson",
    Email: "emily.wilson@example.com",
    Age: 28,
    Phone: "+888888888",
    Access: "manager",
  },
];
